The initial pull request
prNickinv/neural-network pull request #1
Opened 2024-01-18 07:48 UTC by prNickinv

2024-02-05 19:38 UTC, DimaTrushin requested changes
Обрати внимание, что я не повторял замечания. Если одна и та же ошибка всречалась несколько раз, я комментировал лишь единожды. Потому я ожидаю, что ты поправишь все аналогичные замечания всюду.

Есть несколько глобальных проблем. Ты вводишь какую-то неимоверную мешанину из типов. В итоге это только мешает читать код. Ты путаешь имя типа с именем переменной. Оставь только нужные типы и не дублируй это говно по тысячу раз.

Вторая проблема -- у тебя куча неявных зависимостей одной части кода от другой. Ты не передаешь данные явно, а все время их передаешь через "глобальные даннные" в виде переменных класса.

Самое ужасное -- это какая-то дичь с шаблонными параметрами в нейросети. Какого хуя? Так быть не должно. Ты делаешь что-то кардинально не верное. Все делай в run-time. И тогда ты поймешь, где ошибаешься.

Ну и последнее. Никогда не инициализируй рандом случайным не детерминированным сидом. Ты не сможешь ничего протестировать. У тебя будут не репродуцируемые ошибки, которые ты не сможешь никогда отловить и поправить.

2024-02-05 19:38 UTC, DimaTrushin commented on .clang-tidy
> +readability-use-anyofallof'
Добавь пустую строку в конце каждого файла. Дело в том, что гит на это ругается и пользователь твоего репозитория будет видеть сообщения об ошибках от гита. Не делай так.
Добавить в clang-format правило:
InsertNewlineAtEOF: true

2024-02-05 19:38 UTC, DimaTrushin commented on CMakeLists.txt
> +set(CMAKE_CXX_STANDARD 17)
Надо добавить
```cpp
set(CMAKE_CXX_STANDARD_REQUIRED True)
```
Иначе cmake может откатиться к более младшему стандарту.

2024-02-05 19:38 UTC, DimaTrushin commented on main.cpp
> +int main() {
У тебя не отключены exception, потому надо поставить блок на них. Это делается так
```cpp
#include "NeuralNetwork.h"
#include "Except.h"

int main() {
  try {
    nn::run_all_tests();
  } catch(...) {
    except::react();
  }
  return 0;
}
Except.h
namespace except {
void react();
}
Except.cpp
#include "Except.h"

namespace except {
void react() {
  try {
    throw;
  } catch(std::exception& e) {
    // обрабатываешь известные исключения
  } catch(...) {
    // обрабатываешь незивестные исключения
  }
}
}
```

2024-02-05 19:38 UTC, DimaTrushin commented on main.cpp
> +  }
Код до этой строчки -- это всего лишь создание данных для тестирования. Выдели этот код в отдельный модуль, который будет предоставлять доступ к данным или как минимум просто возвращать данные. Я бы тут хотел видеть всего пару строчек вида
```cpp
Data train_data = generateTrainData(...);
Data validation_data = generateValidationData(...);
```
Если эти два вызова должны быть согласованы, то можно создать объект с внутренним состоянием, через которое производится согласование данных.

2024-02-05 19:38 UTC, DimaTrushin commented on main.cpp
> +  std::vector<std::pair<Eigen::VectorXd, Eigen::VectorXd>> example_data;
Не используй std::pair, потому что пользователю не понятно, что значат first и second. Заведи struct с нужным именем и нужными названиями полей. И тогда пользователь сможет по нормальным названиям обращаться к элементам структуры.

2024-02-05 19:38 UTC, DimaTrushin commented on main.cpp
> +  std::vector<std::pair<Eigen::VectorXd, Eigen::VectorXd>> example_data;
Не используй сырые типы вроде Eigen::VectorXd. Сделай using Vector = Eigen::VectorXd; и после этого везде используй псевдоним.

2024-02-05 19:38 UTC, DimaTrushin commented on main.cpp
> +  std::mt19937 generator(rd());
Блять. Никогда, сука, никогда не инициализируй генератор не детерминистски. Вот как ты это говно будешь тестировать? Вот упадет у тебя код при исполнении или выдаст ошибку, и ты ее вообще никогда в жизни не сможешь репродуцировать. Убрать это говно. И сделать константный сид.

2024-02-05 19:38 UTC, DimaTrushin commented on main.cpp
> +  std::vector<std::pair<Eigen::VectorXd, Eigen::VectorXd>> example_data;
Если тебе нужны случайные данные, то есть библиотека EigenRand.

2024-02-05 19:38 UTC, DimaTrushin commented on main.cpp
> +  NeuralNetwork::Network<NeuralNetwork::Sigmoid, NeuralNetwork::MSE>
Охуенно хуевый дизайн. У тебя количество нелинейных функций определяется в compile-time, а количество слоев и их размеров в run-time. Это просто адовый адок. Переделать. Или все в compile-time и одновременно, или все в run-time и одновременно. Либо уж тогда нужно builder pattern использовать, чтобы разнести все эти данные друг от друга.

2024-02-05 19:38 UTC, DimaTrushin commented on main.cpp
> +      example_net(layers_data, 2.0 / 100, 1, 50);
Вот что это за хрень в виде магических констант передано в нейросеть? Готов поклясться, что это данные релевантные только для обучения. И потому не должны передаваться в конструкторе, а должны быть аргументами метода тренировки.

2024-02-05 19:38 UTC, DimaTrushin commented on main.cpp
> +}
Кирпичи, строитель ты мой.

2024-02-05 19:38 UTC, DimaTrushin commented on Sigmoid.h
> +      std::function<Eigen::VectorXd(const Eigen::VectorXd&)>;
Для функции активации ты догадался псевдоним использовать. Но вот почему не использовать для Vector и Matrix?

2024-02-05 19:38 UTC, DimaTrushin commented on Sigmoid.h
> +class Sigmoid {
Плохое имя. Дело в том, что Sigmoid, это частный случай функции активации. А потому лучше класс назвать ActivationFunction. И придумать другое название для юзинга внутри.

2024-02-05 19:38 UTC, DimaTrushin commented on Sigmoid.h
> +  ActivationFunction Activate() const;
Это что за хуево заклинание: "Активейт!" и хуем машешь вместо волшебной палочки. Такой интерфейс приведет к нарушению уровня доступа, тебе придется писать код вида
```cpp
Sigmoid d;
d.Activate()(args);
```
Это трындец какой капец. Почему не сделать нормальный метод apply или evaluate с аргументом Vector?

2024-02-05 19:38 UTC, DimaTrushin commented on Sigmoid.h
> +  using SampleVector = Eigen::VectorXd;
Не надо в типе подчеркивать, что это сампл. Тебе лишь важно, что это вектор столбец и все. Вот можно подчеркнуть, что это будет вектор строка, если понадобится и в Eigen есть соответствующий тип.

2024-02-05 19:38 UTC, DimaTrushin commented on Sigmoid.h
> +      }};
Почему в header-е? Убрать в cpp файл. И сделай это статическими функциями, а не переменными.

2024-02-05 19:38 UTC, DimaTrushin commented on Sigmoid.h
> +#include <cmath>
Убрать лишние хедеры.

2024-02-05 19:38 UTC, DimaTrushin commented on Sigmoid.cpp
> +Sigmoid::ActivationFunction Sigmoid::Activate() const {
Надо поставить assert-ы на всех методах доступа к std::function. Дело в том, что у тебя разрешена мув семантика и потому после мува объект может не содержать соответствующий std::function заполненным. И еще стоит добавить operator bool() const для проверки, что в объекте что-то лежит, чтобы проверять assert-ами на ошибки снаружи.

2024-02-05 19:38 UTC, DimaTrushin commented on RegularNode.h
> +  using LearningRate = double;
LearningRate это не тип, а переменная. Тип все таки double.

2024-02-05 19:38 UTC, DimaTrushin commented on RegularNode.h
> +  using BiasStructure = Eigen::VectorXd;
Зачем обманывать пользователя. У тебя везде используются матрицы и вектора, а тут ты с чего-то вдруг решил WeightsStructure использовать. Убрать и сделать нормальные юзинги вида Matrix и Vector.

2024-02-05 19:38 UTC, DimaTrushin commented on RegularNode.h
> +  using JacobianMatrix = Eigen::MatrixXd;
Матрица якоби по типу ничем не отличается от матрицы весов. Убрать все эти лишние ненужные типы. Назначение будет видно из имени переменной, а не типа.

2024-02-05 19:38 UTC, DimaTrushin commented on RegularNode.h
> +  RegularNode();
С хуя у тебя тут дефолтный конструктор да еще и не по умолчанию!?

2024-02-05 19:38 UTC, DimaTrushin commented on RegularNode.h
> +  using CoefficientFunction = std::function<double(double)>;
С хуя этот тип у тебя публичный?

2024-02-05 19:38 UTC, DimaTrushin commented on RegularNode.h
> +                                          const JacobianMatrix&);
Почему не константный метод? У тебя что какое-то состояние меняется при этом?

2024-02-05 19:38 UTC, DimaTrushin commented on RegularNode.h
> +  BiasStructure gradient_bias_;
Тут одно из двух. Либо ты хранишь не только поправки градиентов, но и значение переданное на входе. Либо ты не хранишь ничего. Ну и названия ужасно длинные.

2024-02-05 19:38 UTC, DimaTrushin commented on RegularNode.h
> +  static inline CoefficientFunction coefficient_function_;
Какого хрена эта штука статическая? Ты что у всего класса единую функцию используешь? ЭТо дичь какая-то. Кроме того у статических переменных есть проблемы с lifetime. Убрать и сделать нормальную не статическую переменную. Кроме того, непонятно нахуя надо было целый класс ActivationFunction создавать, если ты тут руками опять все то же самое пишешь. Убрать и переделать.

2024-02-05 19:38 UTC, DimaTrushin commented on RegularNode.h
> +  static void SetCoefficientFunction(LearningRate, SizeType);
Это что еще за хрень по манипуляции с глобальными данными!? Это явно ошибка дизайна. У тебя не должны все регулярные слои иметь неконстантное общее данное. Это пиздец как плохо.

2024-02-05 19:38 UTC, DimaTrushin commented on RegularNode.h
> +  void UpdateParameters();
Охуеть. Функция, которая ничего не принимает, ничего не возвращает, но при этом что-то делает! Это автоматически означает, что ты только манипулируешь глобальным состоянием. То есть внутри этой функции все взаимодействует со всем в любом случаном порядке. Это ничем не лучше, чем глобальные переменные и глобальные функции. Ты просто завернул все это в класс. Никогда так не делай. Изменить и сделать явную передачу нужных аргументов.

2024-02-05 19:38 UTC, DimaTrushin commented on RegularNode.h
> +
Убрать лишние вертикальные пробелы между функциями.

2024-02-05 19:38 UTC, DimaTrushin commented on RegularNode.h
> +  using SizeType = int;
Плохо. Надо using Index = Eigen::Index; Пользуйся типами, от которых ты зависишь. У Eigen для этого есть свой тип.

2024-02-05 19:38 UTC, DimaTrushin commented on RegularNode.cpp
> +RegularNode::RegularNode() = default;
1) Дефолтный конструктор всегда объявляй в самом классе.
2) Не понятно, зачем тебе тут не дефолтный конструктор. Это ошибка дизайна.

2024-02-05 19:38 UTC, DimaTrushin commented on RegularNode.cpp
> +RegularNode::RegularNode(RegularNode::SizeType in_dim,
Внутри типа тебе не надо пользоваться квалификатором доступа, пиши просто SizeType. Ну или Index, по аналогии с Eigen.

2024-02-05 19:38 UTC, DimaTrushin commented on RegularNode.cpp
> +          out_dim, in_dim, []() { return NormalRandom()(); })),
Что мешало сделать функцию, которая возвращает сразу нужную матрицу
```cpp
: weights_(Random::Normal(out_dim, in_dim),
```
И все. И не надо мучиться и срать в бутылку. Это нарушение уровня абстракции. Чтобы было проще, есть библиотека EigenRand, которая уже все это умеет делать.

2024-02-05 19:38 UTC, DimaTrushin commented on RegularNode.cpp
> +  weights_ -= gradient_weights_.unaryExpr(coefficient_function_);
Что за хуйня тут происходит? Сжечь компьютер и потом переписать код на новой машине, чтобы видны были все зависимости явно.

2024-02-05 19:38 UTC, DimaTrushin commented on RegularNode.cpp
> +RegularNode::SampleVector RegularNode::ApplyLinearModification(
Все методы сделать константными.

2024-02-05 19:38 UTC, DimaTrushin commented on ReLu.h
> +class ReLu {
Нахуя заводить еще один класс, который один в один повторяет Sigmoid? Сделай один класс ActivationFunction и инициализируй по разному его объекты. Ты только лишаешь себя возможности хранить сигмоид и релу в одной переменной.

2024-02-05 19:38 UTC, DimaTrushin commented on RegularNode.cpp
> +          out_dim, in_dim, []() { return NormalRandom()(); })),
Ты создаешь один и тот же Random объект, потому у тебя все эти вызовы дают одни и те же результаты. У тебя вообще нет никакой случайности. Надо сделать глобальный Random.

2024-02-05 19:38 UTC, DimaTrushin commented on NormalRandom.h
> +  double operator()();
const

2024-02-05 19:38 UTC, DimaTrushin commented on NormalRandom.cpp
> +NormalRandom::NormalRandom() : generator_(rd_()) {}
Молись, чтобы я больше не нашел подобной строчки в коде.

2024-02-05 19:38 UTC, DimaTrushin commented on Network.h
> +template<typename ActivationFunctionType, typename LossFunctionType>
Убрать шаблонный тип. Это непонятно что значит. Это дичь, ересь, и полная хуета. Это ошибка дизайна и так не должно быть. У тебя у каждого слоя может быть своя функция активации и информацию об этом надо передавать в run-time.

2024-02-05 19:38 UTC, DimaTrushin commented on Network.h
> +          BatchSize batch_size, EpochsNumber epochs_number)
Из всего этого, Только размеры слоев имеют смысл. Все осталное -- детали для обучения, которые передаются в момент обучения, а не в момент конструирования.

2024-02-05 19:38 UTC, DimaTrushin commented on Network.h
> +  Network(const Dimensions& dimensions, LearningRate learning_rate,
Ты тут сумел завуальировать, что Dimensions это std::vector<int>. Никогда не принимай конкретный контейнер для инициализации. Если у тебя есть другой контейнер, который может к нему конвертироваться, это произойдет и ты не заметишь разницы. Например initializer_list у тебя по умолчанию может конвертнуться в вектор. В итоге ты будешь иметь лишнюю копию с данными во время конструирования. Не делай так. Либо передавай initializer_list явно, либо итераторы.

2024-02-05 19:38 UTC, DimaTrushin commented on Network.h
> +        generator_(rd_()) {
Блять, язнал, что рано радоваться.

2024-02-05 19:38 UTC, DimaTrushin commented on Network.h
> +      CompleteEpoch(training_data);
Что значит completeEpoch? Название абсолютно не информативно.

2024-02-05 19:38 UTC, DimaTrushin commented on Network.h
> +    std::iota(iterating_order_.begin(), iterating_order_.end(), 0);
Это надо завернуть во view объект. А не размазывать его кишки тут. По сути, ты хочешь сделать следующее. Ты создаешь view вектор, который привязан к training_data и потом уже шафлишь его и доступ делаешь через него. Вот эти две строчки это просто часть конструктора для view_vector.

2024-02-05 19:38 UTC, DimaTrushin commented on Network.h
> +    for (int i = 0; i != epochs_number_; ++i) {
У тебя должнеа быть возможность прекратить раньше, когда уже достигнута пороговая точность.

2024-02-05 19:38 UTC, DimaTrushin commented on Network.h
> +  using Dimensions = std::vector<int>;
У тебя тут ад из типов. Сделай порядок из небольшого числа нормальных типов.

2024-02-05 19:38 UTC, DimaTrushin commented on Network.h
> +    }
Нарушение уровня абстракции. Ты выше тасуешь данные одной строчкой, а тут выполняешь низкоуровневую работу. В общем, хреново написано и читать не возможно. Ну и названия с сокращениями и безумно длинные. Придумай что-то более разумное.

2024-02-05 19:38 UTC, DimaTrushin commented on Network.h
> +  Dimensions dimensions_;
Зачем хранить размерности, если их и так знают слои? Это лишние данные.

2024-02-05 19:38 UTC, DimaTrushin commented on Network.h
> +  LossFunctionDerivative loss_function_derivative_;
Вот это все лишние данные, которые нужны только при обучении.

2024-02-05 19:38 UTC, DimaTrushin commented on Network.h
> +  std::mt19937 generator_;
Вот этому тут не место. Это детали глобального рандома.

2024-02-05 19:38 UTC, DimaTrushin commented on Network.h
Это говно надо как минимум отрефакторить. Надо убрать ебаную глобальную зависимость сети от функции активации и от лосс функции. И передавать функции активации во время конструирования в конструкторе для каждого слоя независимо. А все остальные данные только в функции обучения.

2024-02-05 19:38 UTC, DimaTrushin commented on ActivatedNode.h
> +class ActivatedNode {
Это что за хрень со случайным данным внутри?

2024-02-05 19:38 UTC, DimaTrushin commented on Layer.h
> +  ActivatedNode activated_node_;
Блять, а что же тогда было такое в RegularNode за функция, которая покоэффициентно применялась!? Что вообще происходит в этом коде? Это ебанина какая-то а не слой нейросети.

2024-02-05 19:38 UTC, DimaTrushin commented on Layer.h
> +  SampleVector input_vector_;
Зачем?

2024-02-05 19:38 UTC, DimaTrushin commented on Layer.h
> +  BackPropVector back_prop_vector_;
Зачем?
Это все данные для обучения. Пусть метод обучения их и хранит.

2024-03-30 16:26 UTC, prNickinv commented
Внес изменения:

1) Лишние типы с using убраны.
2) Константные сиды в рандомах поставлены, рандомный генератор сделан статичным.
3) EigenRand подключен.
4) assert-ы на при обращении к функциям активации и потерь поставлены. Метод operator bool добавлен.
5) Шаблонного класса Network больше нет. 
6) Поправки градиента будут храниться в классе Layer вместе с входным вектором (input_vector) и pre_activated_vector (вектор Ax + b после линейного преобразования), т.к. он нужен для расчета матрицы Якоби и кажется их удобнее вместе хранить в Layer.
7) Функции активации и размерности слоев теперь принимаются как std::initializer_list.
8) В отельный класс вынесено создание view_vector-a, хранящего индексы обращения к данным.
9) Добавлена ранняя остановка обучения с заданием через enum class.
10) Добавлен enum class Task
`enum class Task {
  Regression,
  Classification,
  SoftMaxCEClassification,
  Unspecified
};`
Он нужен для того, чтобы можно было выбрать правильные метрики для валидации, а SoftMaxCEClassification нужна, тк в случае комбинации Softmax на последнем слое и CrossEntropy как функции потерь, последний слой надо обрабатывать по-особому.

11) Добавлены тесты на mnist и mnist-fashion. Сами датасеты загружены через стороннюю библиотеку, подключенную как submodule. Добавлен класс Data, где эти данные приводятся к виду, который принимает нейросеть.
Но оказалось, что ни mnist ни mnist-fashion не предоставляют валидационных данных, поэтому я использовал тестовые данные для валидации. В целом, при необходимости можно разбить данные для обучения на две части и одну использовать для валидации. 
По обучению пока удалось добиться около 80% точности на нормализованных тестовых данных. И до 95% для бинаризованного мниста.

Имеющиеся проблемы (те, что смог заметить):
1) Длинные названия. Пока не могу придумать ничего более короткого и при этом интуитивно понятного.
2) Я добавил в clang-format 
`InsertNewlineAtEOF: true`
И локально эти пустые строки в конце у меня есть, но после git push тут на гитхабе они все исчезли по непонятным причинам. Пока не знаю, как решать эту проблему. 
3) Т.к. методы для проверки валидности функций активации/потерь константные, clang-tidy хочет отметить [[nodiscard]], но ведь эти проверки обычно производятся в выражении if и нам не надо сохранять результат, нужно ли подавить предупреждение через //NOLINT?
4) Clang-tidy также ругается, когда передаем размер в функцию, ожидающую int или когда делим double на размер. Нужно ли в этих случаях применять static_cast?

2024-04-23 15:27 UTC, prNickinv commented
Добавил:
1) Возможность сохранения модели в файл
2) Чтение из файла. Но для этого понадобилось добавить дефолтные конструкторы, чтобы можно было делать так:

`std::ifstream file("file.txt");`

`NeuralNetwork::Network network;`

 `file >> network;`

Но возможно имеет смысл вместо перегруза `>>` сделать конструктор от потока, но там есть момент, что функция, которая должна подтянуть верную функцию активации может бросить исключение, если в файле указан тип функции, которые мы не знаем. Не уверен, насколько это приемлемо будет тут допускать исключения в конструкторе

3) Очень часто clang-tidy настаивает на использовании директивы `[[nodiscard]]`,  я добавил в ряд мест, но кажется код становится от этого менее читаем. Насколько хорошей практикой считается использование этой директивы?

2024-04-23 19:46 UTC, prNickinv commented
Добавил конструкторы для Layer и Network, который принимают потоки.
Получилось так:

- в Network два конструктора: первый принимает только поток и предназначен для ситуации, когда в файле все функции активации таковы, что мы имеем их имплеменатцию и можем сами подтянуть. 
- второй принимает помимо потока еще список инициализации из функций активации. Т.е в случае, если у пользователя в файле есть какие-то свои функции, то он может их передать и тогда мы тоже их инициализировать. Еще это можно использовать, если пользлователь просто хочет использовать другие функции активации, чем в файле.
- В Layer вышел один конструктор, который принимает поток и функцию активации, которой по дефолту пустая. И уже внутри конструктора идет проверка - если функция передана, то берем ее. Если нет - то читаем из файла и ищем у себя. Если не нашли - бросаем исключение.
Правда в Layer конструктор принимает функцию активации по константной ссылке. Нужно ли еще вариант с rvalue ссылкой? Просто там неприятность, что тело конструктора будет идентичным и оно вышло и так громоздким.

Будет ли такой вариант нормальным? И оставлять тогда или лучше убрать перегруз `operator>>`

Кстати, а стоит ли еще предусмотреть опцию изменения функций активации уже после того как нейросеть была создана?

2024-05-03 21:53 UTC, prNickinv commented
Обнаружилась проблема, что при подключении eigen через сабмодули, идет не 3.4.0 версия, а другая несовместимая с EigenRand. Исправил на 3.4.0

Еще момент возник. Команда

```cmake
find_package(Eigen3 3.4 NO_MODULE)
```

ищет локальный eigen, а не сабмодульный, тк при подключении через сабмодуль нет файла FindEigen3.cmake, сейчас я добавил такое 

```cmake
if (NOT Eigen3_FOUND)
    include_directories(${CMAKE_SOURCE_DIR}/third-party-library/eigen/)
endif ()
```
что если нет у пользователя локально eigen, то будет использоваться сабмодуль. Или лучше вообще убрать find_package(Egien3), чтобы только сабмодульная версия использовалась?

2024-05-04 11:09 UTC, prNickinv commented
Все-таки убрал опцию локального eigen, тк таким образом мы точно гарантируем совместимую версию eigen + так можно компилировать проект как библиотеку опцией
```cmake
add_library(net-lib ${NEURAL_NETWORK})
```
И тогда тесты могут использовать уже скомпилированные src файлы. При локальном eigen оно так не собиралось.

Начал добавлять гугл-тесты

2024-05-25 13:42 UTC, prNickinv commented
Возникло несколько вопросов/проблем:

1) Добавил файл с глобальными using-ми. Вот здесь возник вопрос. Если я в "GlobalUsing.h" подключаю хедеры на std::vector и Eigen/Dense, то во всех классах, где я буду делать 
```cpp 
#include <GlobalUsings.h>
```
не нужно ведь отдельно еще подключать std::vector, Eigen?

2) Добавил оптимизаторы AdamW, Momentum с использованием std::variant.
Здесь такой момент. У них есть свое состояние (матрицы, векторы, которые обновляются по ходу обучения), так вот нужно ли их инициализировать по умолчанию (в конструкторе или хедере?) нулями?
Функционально я в этом необходимости не вижу, тк сейчас все устроено так:

```cpp
// Создаем нейросеть с заданной архитектурой
  auto network =
      NeuralNetwork::Network({784, 100, 10},
                             {NeuralNetwork::ActivationFunction::ReLu(),
                              NeuralNetwork::ActivationFunction::SoftMax()});
// Устаналиваем оптимизатор
network.SetOptimizer(NeuralNetwork::AdamWOptimizer());
```
и дальше уже внутри будет вызван метод, которой приведет этот переданный оптимизатор к нужной размерности и заполнит нулями. И поэтому необходимости в предварительной инициализации полей
```cpp
Matrix v_w_;
Vector v_b_;
```
не вижу.
Сейчас для моментума так и есть, а для Адама я поставил дефолтную инициализацию матрицами размера 1x1 с нулем.
Как здесь будет более корректно сделать?

3) Есть сомнения с чтением из файла.
Сейчас по сути две версии есть: инициализировать нейросеть по информации из файла, применив конструктор от потока:

```cpp
Network net(filestream);
```
А есть через оператор >>
```cpp
Network net; 
filestream >> net;
```
Насколько разумно делать через >>? Получается, что этот оператор, в отличие от конструктора, оперирует с уже существующим объектом и тут несколько сомнений:

a) Тело этого оператора практически полностью повторяет тело конструктора от потока, что, наверное, не очень хорошо
b) Мы таким образом даем пользователю возможность через оператор >> в любом месте его программы менять приватные поля объектов классов Network и Layer, там параметры различные и тд, что звучит опасно.
Вот здесь можно две тактики придумать: (1) "Пользователь сам виноват, что-то не то сделал, мы ему лишь дали опцию" и оставить перегрузы либо же (2) "Не будем искушать пользователя" и уберем перегруз, оставив только конструктор от потока

4) У Mnist (и MnistFashion тоже) дается 60000 тренировочных данных и 10000 для тестирования, при этом для валидации не дается ничего. Сейчас я сделал так, что у меня эти 10000 тестовых данных используется именно для валидации, чтобы можно было наглядно показать, как меняются метрики по эпохам, а непосредственно именно тестирования нет.
Будет ли ОК так оставить?

В принципе, можно разбить тренировочный датасет на две части: допустим, 50000 для обучения и 10000 для валидации. А те 10000 уже на тестирование. Но тогда мы сокращаем выборку, что тоже так себе.

5) В функциях активации у меня есть численно нестабильные версии сигмоиды и софтмакса (стабильные тоже есть). Их можно оставить или лучше выкинуть?

2024-05-26 12:07 UTC, prNickinv commented
Внес изменения в структуру. Теперь все действия по обновлению параметров будут делать методы классов оптимизаторов, а не Layer.

Еще хотел объяснить один момент: у меня каждый слой имеет в качестве поля оптимизатор. Дело в том, что передавать оптимизатор как аргумент функции Train у меня не получится, тк тогда не выйдет сохранять состояние оптимизатора в файл, тк за пределами Train его бы просто не существовало. И поэтому нужно, чтобы сама нейросеть имело это состояние.  

Также у меня оптимизаторы хранятся именно в классе слоя, а не нейросети, здесь из соображения, что у каждого слоя в определенный момент времени есть свое состояния оптимизатора, а раз так, то пусть именно он его и хранит, а Network уже пусть занимается коммуникацией с пользователем и делегированием полномочий более низким классам.

По памяти это не должно вызвать проблемы, тк что Network хранил бы все состояния всех слоев, что каждый слой знает только про себя.

2024-06-02 18:39 UTC, prNickinv commented
Добавил юнит-тестов 

Заменил условные переходы на использование std::visit в Layer для обновление параметров через оптимизатор. Выглядит более компактно и не нужно ничего менять в случае добавления новых оптимизаторов.

Разбил функции по получения данных и валидации на несколько частей.

Добавил планировщики скорости обучения (Learning Rate Scheduler). Пока только экспоненциальный.
Тоже через std::varinat. Но здесь есть момент, что будет поддержка, как и константой скорости обучения (без планировщика) и через него. Поэтому теперь в оптимизатор добавился шаблонный конструктор на случай планировщика (по константной ссылке принимает). 
Для случай константного lr (типа double) остается старый конструктор

Но из-за того, что нужно поддерживать работу и с планировщиком и без него, возникает сложность с std::visit, так теперь нужно передавать такой функтор, чтобы он либо применял метод GetLearningRate из планировщика, либо возвращал константный. Для этой логики добавил паттерн  Overload в SchedulerUtils

2024-06-02 19:50 UTC, prNickinv commented
Добавлен полиномиальный планировщик. В случае, если номер итерации превышает заданный порог, дальнейшего сокращения не производится, а устанавливается некоторая заданная минимальная скорость обучения

Также есть возможность сохранять состояние планировщиков в файл и загружать из него

2024-06-02 22:40 UTC, prNickinv commented
Вывел из конструктора слоя от потока задание оптимизатора в отдельную статичную функцию. Статичную, тк ей не нужен экземпляр класса, к тому же она будет вызываться из конструктора

По результатам обучения пока лучшее, что получилось это:
1) 6 эпох точность 97.34% на тестовых данных для обычного mnist
2)  8 эпох точность 87.1% на тестовых данных для mnist-fashion

2024-06-03 01:22 UTC, prNickinv commented
Добавлен оптимизатор NAdam

2024-06-03 23:15 UTC, prNickinv commented
В процессе чистки кода, хочу прояснить ряд моментов:

1) Сейчас проставлю [[nodiscard]] там, где clang-tidy просит. Наконец-то я разобрался, как он работает. Я думал, что он как кидает предупреждения при любой ситуации неприсовения результата в переменную, что меня и смушало, но оказлось он только на такое ругается
```cpp
func.IsEmpty();
```
А на применение таких методов в условных переходах он не ругается. Так что лучше поставить, думаю, так для константных методов подобное выше не должно являться ожидаемым поведением

2) В констурторах везде оставил скобочки (), пусть единоообразно будет. Но все равно интересно, как лучше/безопаснее? Слишком разнится информация везде

3) Там где clang-tidy ругается на narrowing, буду делать static_cast, так особо другого выхода нет. Например, нужно делать double на size_t и подобное (при подсчете метрик, например)

4) В оптимизаторах в методе ``GetLearningRate`` в лямбда-функцию передается планировщик по неконстаной ссылке. Это намеренно, тк внутренний метод планировщика, который та зовется, должен инкременитровать шаг. Но больше он ничего не делает, поэтому каких-то side effects быть не должно. 
У взаимодействия Layer и оптимизаторов (в функции ```UpdateParameters``) тоже такой момент есть по той же причине

5) В оптимизаторах есть дефолтные гиперпараметры, сейчас они такое
```cpp
static constexpr double default_weights_decay_{0.01};
double weights_decay_{default_weights_decay_};
```
Так нормально делать? Или лучше дефолты выставлять в аргументы констуктора?

2024-06-03 23:36 UTC, prNickinv commented
Еще clang-tidy в планировщиках говорит, что должно быть так
```cpp
 double initial_learning_rate_{};
  int decay_steps_{};
  double decay_rate_{};
  int step_{};
```
С этими скобками, иначе конструктор от потока не инициализирует поля. Но при это работает.
Так нормально делать или можно как-то по-другому? Еще как вариант вижу сделать эти штуки с пустыми скобками в списке инициализации перед этим конструктором. Или вообще  лучше просто задать какой-то дефолт. Хотя если пользователь берет планировщик, дефолтные значения как-то не очень правильой историей кажутся

2024-07-23 15:32 UTC, nilovlev approved these changes

2024-07-23 15:35 UTC, nilovlev approved these changes

2024-07-23 19:27 UTC, merged